-- script.sql

DROP TABLE IF EXISTS ODONTOLOGOS;
CREATE TABLE ODONTOLOGOS (
ID INT PRIMARY KEY AUTO_INCREMENT,
MATRICULA VARCHAR(100) NOT NULL,
NOMBRE VARCHAR(100) NOT NULL,
APELLIDO VARCHAR(100) NOT NULL);